const wchar_t* z_strings[] = { L"",L"Plan XY",
L"No",
L"Yes",
L"OK",
L"Cancel",
L"Light/Dark",
L"New",
L"Open",
L"Save",
L"Save as...",
L"Exit",
L"Default",
L"Light",
L"Dark",
L"Restart application to apply.",
L"Help",
L"Main",
L"Data",
L"Time Constraints",
L"Space Constraints",
L"Generator",
L"File",
L"Basic",
L"Teachers",
L"Activities",
L"Lessons",
L"Students",
L"Subactivities",
L"Tags",
L"Spaces",
L"Teacher",
L"Activity",
L"Lesson",
L"Student",
L"Subactivity",
L"Tag",
L"Space",
L"Last name",
L"First name",
L"Parameters",
L"Add",
L"Name",
L"Comments",
L"Hours",
L"Selected",
L"Delete",
L"Long name",
L"Code",
L"Buildings",
L"Building",
L"Rooms",
L"Room",
L"Infrastructure",
L"Capacity",
L"Classes",
L"Institution Name",
L"Days",
L"Day",
L"Threads",
L"Generate now",
L"Generating timetables...",
L"Main Building",
L"Options",
L"Years",
L"Year",
L"Groups",
L"Group",
L"Subgroups",
L"Subgroup",
L"Sort",
L"How many timetables to generate",
L"Number of Students",
L"Summary",
L"Open Results Folder",
L"Results",
L"Group ID",
L"Not available times",
L"Filter",
L"Active",
L"Filter type",
L"View",
L"Entry",
L"New entry",
L"Percentage",
L"Select",
L"Home room",
L"Assignments",
L"Assignment",
L"Warnings",
L"Timetable",
L"Basic Compulsory Time",
L"Class",
L"Min days/week",
L"Max days/week",
L"Active",
L"Max gaps/day",
L"Max gaps/week",
L"No work two consecutive days",
L"Max hours/day",
L"Day limits",
L"Week limits",
L"Max span/day",
L"One day exception",
L"Min hours/day",
L"Max continuous hours",
L"Import CSV...",
L"Building name,Building long name,Building code,Building comments",
L"Minutes to wait",
L"Room name,Room long name,Building code,Room capacity,Building comments",
L"Number of hours",
L"Kid name,Kid code",
L"Creating students is not needed to generate a timetable but it is useful for exporting it for each student.",
L"Read only",
L"Enabled",
L"Disabled",
L"Export",
L"Page/Teacher",
L"Teachers/Week",
L"Disable time constraints",
L"Disable space constraints",
L"Statistics",
L"Level 1",
L"Level 2",
L"Level 3",
L"Run",
L"Settings",
L"Plan XY files (*.fet)",
L"This is the Basic information for your institution.",
L"Each institution has at least one building and each building has at least one room. You can add or import new buildings and rooms.",
L"Search",
L"You can add or import teachers for your institution.",
L"Teacher name,Teacher hours",
L"You can add or import lessons for your institution.",
L"Lesson name,Lesson code",
L"You can have up to 3 class levels.",
L"Tags are optional. They are useful to apply certain time or space constraints to a group of activities.",
L"You assign teachers to lessons and classes with activities. The assignments are an easier way to create activities by first selecting a teacher.",
L"You assign teachers to lessons and classes with activities. ",
L"Max room changes",
L"Max room changes (Interval)",
L"From",
L"To",
L"Max building changes",
L"Max bulding changes (Interval)",
L"About",
L"Preferred rooms",
L"Preferred room",
};

#define MAX_LANG 147



