const wchar_t* z_strings_fr[] = {L"",L"Plan XY",
L"Non",
L"Oui",
L"OK",
L"Annuler",
L"Clair/Sombre",
L"Nouveau",
L"Ouvrir",
L"Enregistrer",
L"Enregistrer sous...",
L"Quitter",
L"Par défaut",
L"Clair",
L"Sombre",
L"Redémarrez l'application pour appliquer les changements.",
L"Aide",
L"Principal",
L"Données",
L"Contraintes de temps",
L"Contraintes d'espace",
L"Générateur",
L"Fichier",
L"Basique",
L"Enseignants",
L"Activités",
L"Leçons",
L"Étudiants",
L"Sous-activités",
L"Étiquettes",
L"Espaces",
L"Enseignant",
L"Activité",
L"Leçon",
L"Étudiant",
L"Sous-activité",
L"Étiquette",
L"Espace",
L"Nom de famille",
L"Prénom",
L"Paramètres",
L"Ajouter",
L"Nom",
L"Commentaires",
L"Heures",
L"Sélectionné",
L"Supprimer",
L"Nom complet",
L"Code",
L"Bâtiments",
L"Bâtiment",
L"Salles",
L"Salle",
L"Infrastructure",
L"Capacité",
L"Classes",
L"Nom de l'institution",
L"Jours",
L"Jour",
L"Threads",
L"Générer maintenant",
L"Génération des emplois du temps...",
L"Bâtiment principal",
L"Options",
L"Années",
L"Année",
L"Groupes",
L"Groupe",
L"Sous-groupes",
L"Sous-groupe",
L"Trier",
L"Combien d'emplois du temps générer",
L"Nombre d'étudiants",
L"Résumé",
L"Ouvrir le dossier des résultats",
L"Résultats",
L"ID de groupe",
L"Heures non disponibles",
L"Filtrer",
L"Actif",
L"Type de filtre",
L"Afficher",
L"Entrée",
L"Nouvelle entrée",
L"Pourcentage",
L"Sélectionner",
L"Salle principale",
L"Affectations",
L"Affectation",
L"Avertissements",
L"Emploi du temps",
L"Temps obligatoire de base",
L"Classe",
L"Jours min/semaine",
L"Jours max/semaine",
L"Actif",
L"Max d'intervalles/jour",
L"Max d'intervalles/semaine",
L"Pas de travail deux jours consécutifs",
L"Max d'heures/jour",
L"Limites journalières",
L"Limites hebdomadaires",
L"Durée max/jour",
L"Exception d'un jour",
L"Heures min/jour",
L"Max heures continues",
L"Importer CSV...",
L"Nom du bâtiment,Code du bâtiment,Commentaires du bâtiment",
L"Minutes d'attente",
L"Nom de salle,Code salle,Capacité",
L"Nombre d'activités",
L"Nom étudiant,Code étudiant",
L"La création des étudiants n'est pas nécessaire pour générer un emploi du temps mais utile pour l'export par étudiant.",
L"Lecture seule",
L"Activé",
L"Désactivé",
L"Exporter",
L"Page/Enseignant",
L"Enseignants/Semaine",
L"Désactiver contraintes de temps",
L"Désactiver contraintes d'espace",
L"Statistiques",
L"Niveau 1",
L"Niveau 2",
L"Niveau 3",
L"Exécuter",
L"Paramètres",
L"Fichiers Plan XY",
L"Ceci est l'information de base pour votre institution.",
L"Chaque institution a au moins un bâtiment et chaque bâtiment a au moins une salle. Vous pouvez ajouter ou importer de nouveaux bâtiments et salles.",
L"Recherche",
L"Vous pouvez ajouter ou importer des enseignants pour votre institution.",
L"Nom enseignant,Heures enseignant",
L"Vous pouvez ajouter ou importer des leçons pour votre institution.",
L"Nom leçon,Code leçon",
L"Vous pouvez avoir jusqu'à 3 niveaux de classe.",
L"Les étiquettes sont optionnelles. Elles sont utiles pour appliquer certaines contraintes de temps ou d'espace à un groupe d'activités.",
L"Vous assignez des enseignants aux leçons et classes via les activités. Les affectations facilitent la création d'activités en sélectionnant d'abord un enseignant.",
L"Vous assignez des enseignants aux leçons et classes via les activités.",
L"Max changements de salle",
L"Max changements de salle (Intervalle)",
L"De",
L"À",
L"Max changements de bâtiment",
L"Max changements de bâtiment (Intervalle)",
L"À propos",
L"Salles préférées",
L"Salle préférée",
L"La création des parents n'est pas nécessaire pour générer un emploi du temps mais utile pour l'export par parent.",
L"Parents",
L"Parent",
L"Nom parent,Code parent",
L"Collaboration",
L"Partager écran",
L"Rejoindre",
L"Copier clé dans le presse-papiers",
L"En attente des utilisateurs. Envoyez-leur la clé d'invitation et gardez cette fenêtre ouverte.",
L"Entrez la clé d'invitation :",
L"Mode",
L"Par défaut",
L"ID unique",
L"Nom affiché",
L"Pas deux jours consécutifs",
L"Heures de début préférées",
L"À la fin",
L"Mise en veille PC",
L"Arrêt PC",
L"Génération terminée. Arrêt dans 1 minute.",
L"Plages horaires préférées",
L"Début/Fin journée",
L"Heure",
L"Début journée classe",
L"Fin journée classe",
L"Début/Fin journée classe",
L"Début journée enseignant",
L"Fin journée enseignant",
L"Début/Fin journée enseignant",
L"Jours min entre",
L"Autres limites",
L"Min intervalles entre changements de salle",
L"Min intervalles entre changements de bâtiment",
L"Afficher uniquement les entrées",
L"Bienvenue dans Plan XY.\r\nCommencez à concevoir votre emploi du temps dans l'onglet 'Données', ou ouvrez un exemple existant depuis le menu Exemples.",
L"Exemples",
L"Couleur",
L"Exporter FET",
L"Heures de début préférées",
L"Fonctionnalités de sortie",
L"Combinaisons de classes",
L"Actions",
L"Le projet a été modifié. Enregistrer les modifications ?",
L"Heures/activité",
L"Enregistrer le projet d'abord ? Si vous générez un emploi du temps dans un projet enregistré, il sera automatiquement sauvegardé dans le fichier projet.",
L"Êtes-vous sûr de vouloir arrêter la génération de l'emploi du temps ?",
L"Entrées existantes",
L"Entrée existante",
L"Heure de création",
L"Durée",
L"En pause",
L"Intervalles",
L"Nouveau bâtiment",
L"Nouvelle salle",
L"Obligatoire",
LR"(Jours maximum entre)",
LR"(Début/Fin de journée)",
LR"(Début de journée)",
LR"(Fin de journée)",
LR"(Coordonnées)",
L"Éditeur manuel",
L"Ensemble d'activités",
L"Même heure de début",
L"Même jour de début",
L"Même heure+jour de début",
L"Démarrer",
L"Pas de chevauchement",
L"Ensemble d’étiquettes",
L"Importer",
L"Deux sont ordonnées",
L"Deux sont ordonnées (même jour)",
L"Deux sont consécutives",
L"Deux sont groupées",
L"Trois sont groupées",
L"Durée horaire maximale",
L"Écarts minimum entre",
L"Divers",
L"Contrainte",
L"Contraintes",
L"Heures minimales de repos",
L"Circulaire",
L"Inconnu",
L"Ces contraintes FET ne sont pas encore reconnues par PlanXY, mais vous pouvez les modifier manuellement",
L"Occuper le nombre maximal de créneaux horaires de la sélection",
L"Créneaux horaires",
L"Nombre maximal de créneaux horaires",
L"Détacher",
L"Joindre",
L"Le projet contient des données actives détachées. Gérez ces données dans la page « Exécution ».",
L"Gérer les données détachées",
L"Session",
L"Joindre et reprendre",
L"Terminer",
L"Reprendre",
L"Créneaux horaires mutuellement exclusifs",
L"Pause",
};

#define MAX_LANG 243