const wchar_t* z_strings_de[] = {L"",L"Plan XY",
L"Nein",
L"Ja",
L"OK",
L"Abbrechen",
L"Hell/Dunkel",
L"Neu",
L"Öffnen",
L"Speichern",
L"Speichern unter...",
L"Beenden",
L"Standard",
L"Hell",
L"Dunkel",
L"Starten Sie die Anwendung neu, um die Änderungen anzuwenden.",
L"Hilfe",
L"Hauptmenü",
L"Daten",
L"Zeitbeschränkungen",
L"Raumbeschränkungen",
L"Generator",
L"Datei",
L"Grunddaten",
L"Lehrkräfte",
L"Aktivitäten",
L"Unterricht",
L"Schüler",
L"Teilaktivitäten",
L"Tags",
L"Räume",
L"Lehrkraft",
L"Aktivität",
L"Unterricht",
L"Schüler",
L"Teilaktivität",
L"Tag",
L"Raum",
L"Nachname",
L"Vorname",
L"Parameter",
L"Hinzufügen",
L"Name",
L"Kommentare",
L"Stunden",
L"Ausgewählt",
L"Löschen",
L"Langer Name",
L"Code",
L"Gebäude",
L"Gebäude",
L"Räume",
L"Raum",
L"Infrastruktur",
L"Kapazität",
L"Klassen",
L"Name der Einrichtung",
L"Tage",
L"Tag",
L"Threads",
L"Jetzt generieren",
L"Stundenpläne werden generiert...",
L"Hauptgebäude",
L"Optionen",
L"Jahre",
L"Jahr",
L"Gruppen",
L"Gruppe",
L"Untergruppen",
L"Untergruppe",
L"Sortieren",
L"Wie viele Stundenpläne sollen generiert werden",
L"Anzahl der Schüler",
L"Zusammenfassung",
L"Ergebnisordner öffnen",
L"Ergebnisse",
L"Gruppen-ID",
L"Nicht verfügbare Zeiten",
L"Filter",
L"Aktiv",
L"Filtertyp",
L"Ansicht",
L"Eintrag",
L"Neuer Eintrag",
L"Prozentsatz",
L"Auswählen",
L"Stammraum",
L"Zuweisungen",
L"Zuweisung",
L"Warnungen",
L"Stundenplan",
L"Grundlegende Zeitbeschränkungen",
L"Klasse",
L"Min. Tage/Woche",
L"Max. Tage/Woche",
L"Aktiv",
L"Max. Lücken/Tag",
L"Max. Lücken/Woche",
L"Keine Arbeit an zwei aufeinanderfolgenden Tagen",
L"Max. Stunden/Tag",
L"Tageslimits",
L"Wochenlimits",
L"Max. Spannweite/Tag",
L"Eintagesausnahme",
L"Min. Stunden/Tag",
L"Max. aufeinanderfolgende Stunden",
L"CSV importieren...",
L"Gebäudename,Gebäudecode,Gebäudekommentare",
L"Wartezeit in Minuten",
L"Raumname,Raumcode,Kapazität",
L"Anzahl der Aktivitäten",
L"Name des Kindes,Code des Kindes",
L"Das Erstellen von Schülern ist nicht erforderlich, um einen Stundenplan zu generieren, ist aber nützlich für den Export pro Schüler.",
L"Schreibgeschützt",
L"Aktiviert",
L"Deaktiviert",
L"Exportieren",
L"Seite/Lehrkraft",
L"Lehrkräfte/Woche",
L"Zeitbeschränkungen deaktivieren",
L"Raumbeschränkungen deaktivieren",
L"Statistiken",
L"Ebene 1",
L"Ebene 2",
L"Ebene 3",
L"Ausführen",
L"Einstellungen",
L"Plan XY-Dateien",
L"Dies sind die Basisinformationen Ihrer Einrichtung.",
L"Jede Einrichtung hat mindestens ein Gebäude, und jedes Gebäude hat mindestens einen Raum. Sie können neue Gebäude und Räume hinzufügen oder importieren.",
L"Suchen",
L"Sie können Lehrkräfte für Ihre Einrichtung hinzufügen oder importieren.",
L"Name der Lehrkraft,Stunden der Lehrkraft",
L"Sie können Unterrichtsfächer für Ihre Einrichtung hinzufügen oder importieren.",
L"Name des Fachs,Fachcode",
L"Sie können bis zu 3 Klassenstufen haben.",
L"Tags sind optional. Sie sind nützlich, um bestimmte Zeit- oder Raumbeschränkungen auf eine Gruppe von Aktivitäten anzuwenden.",
L"Sie weisen Lehrkräfte Fächern und Klassen über Aktivitäten zu. Zuweisungen erleichtern das Erstellen von Aktivitäten, indem zuerst eine Lehrkraft ausgewählt wird.",
L"Sie weisen Lehrkräfte Fächern und Klassen über Aktivitäten zu.",
L"Maximale Raumwechsel",
L"Maximale Raumwechsel (Intervall)",
L"Von",
L"Bis",
L"Maximale Gebäudewechsel",
L"Maximale Gebäudewechsel (Intervall)",
L"Info",
L"Bevorzugte Räume",
L"Bevorzugter Raum",
L"Das Erstellen von Eltern ist nicht erforderlich, um einen Stundenplan zu generieren, ist aber nützlich für den Export pro Elternteil.",
L"Eltern",
L"Elternteil",
L"Name des Elternteils,Code des Elternteils",
L"Zusammenarbeit",
L"Bildschirm teilen",
L"Beitreten",
L"Schlüssel in Zwischenablage kopieren",
L"Warten auf Benutzer. Bitte senden Sie ihnen den Einladungsschlüssel und lassen Sie dieses Fenster geöffnet.",
L"Geben Sie den Einladungsschlüssel ein:",
L"Modus",
L"Standard",
L"Eindeutige ID",
L"Anzeigename",
L"Keine zwei aufeinanderfolgenden Tage",
L"Bevorzugte Startzeiten",
L"Nach Abschluss",
L"PC-Schlafmodus",
L"PC herunterfahren",
L"Generierung abgeschlossen. Herunterfahren in 1 Minute.",
L"Bevorzugte Zeitfenster",
L"Tagesbeginn/-ende",
L"Zeit",
L"Beginn Unterrichtstag",
L"Ende Unterrichtstag",
L"Beginn/Ende Unterrichtstag",
L"Beginn Lehrertag",
L"Ende Lehrertag",
L"Beginn/Ende Lehrertag",
L"Min. Tage zwischen",
L"Andere Grenzen",
L"Min. Lücken zwischen Raumwechseln",
L"Min. Lücken zwischen Gebäudewechseln",
L"Nur Einträge anzeigen",
L"Willkommen bei Plan XY.\r\nBeginnen Sie mit der Planung Ihres Stundenplans auf der Registerkarte 'Daten' oder öffnen Sie ein vorhandenes Beispiel aus dem Menü Beispiele.",
L"Beispiele",
L"Farbe",
L"FET exportieren",
L"Bevorzugte Startzeiten",
L"Ausgabeeigenschaften",
L"Klassenkombinationen",
L"Aktionen",
L"Das Projekt wurde geändert. Änderungen speichern?",
L"Stunden/Aktivität",
L"Projekt zuerst speichern? Wenn Sie einen Stundenplan in einem gespeicherten Projekt generieren, werden die erzeugten Stundenpläne automatisch in der Projektdatei gespeichert.",
L"Sind Sie sicher, dass Sie die Stundenplangenerierung stoppen möchten?",
L"Vorhandene Einträge",
L"Vorhandener Eintrag",
L"Erstellungszeit",
L"Dauer",
L"Pausiert",
L"Lücken",
L"Neues Gebäude",
L"Neuer Raum",
L"Muss",
LR"(Maximale Tage zwischen)",
LR"(Beginn/Ende des Tages)",
LR"(Beginn des Tages)",
LR"(Ende des Tages)",
LR"(Koordinaten)",
L"Manueller Editor",
L"Aktivitätssatz",
L"Gleiche Startstunde",
L"Gleicher Starttag",
L"Gleiche Startstunde+Tag",
L"Starten",
L"Keine Überschneidung",
L"Etikettensatz",
L"Importieren",
L"Zwei sind geordnet",
L"Zwei sind geordnet (gleicher Tag)",
L"Zwei sind aufeinanderfolgend",
L"Zwei sind gruppiert",
L"Drei sind gruppiert",
L"Maximale Stunden-Spanne",
L"Minimale Lücken zwischen",
L"Verschiedenes",
L"Einschränkung",
L"Einschränkungen",
L"Mindest-Ruhezeiten",
L"Zirkulär",
L"Unbekannt",
L"Diese FET-Beschränkungen sind PlanXY noch nicht bekannt, können jedoch manuell bearbeitet werden",
L"Maximale Zeitfenster aus Auswahl belegen",
L"Zeitfenster",
L"Maximale Zeitfenster",
L"Trennen",
L"Anhängen",
L"Das Projekt enthält aktive getrennte Laufzeitdaten. Verwalten Sie die Laufzeitdaten auf der Seite „Ausführen“.",
L"Getrennte Daten verwalten",
L"Sitzung",
L"Anhängen und fortsetzen",
L"Beenden",
L"Fortsetzen",
L"Wechselseitig ausschließende Zeitfenster",
L"Pause",
};

#define MAX_LANG 243