const wchar_t* z_strings_ro[] = {L"",L"Plan XY",
L"Nu",
L"Da",
L"OK",
L"Anulare",
L"Luminos/Întunecat",
L"Nou",
L"Deschide",
L"Salvează",
L"Salvează ca...",
L"Ieșire",
L"Implicit",
L"Luminos",
L"Întunecat",
L"Reporniți aplicația pentru a aplica modificările.",
L"Ajutor",
L"Principal",
L"Date",
L"Constrângeri de timp",
L"Constrângeri de spațiu",
L"Generator",
L"Fișier",
L"De bază",
L"Profesori",
L"Activități",
L"Lecții",
L"Elevi",
L"Subactivități",
L"Etichete",
L"Spații",
L"Profesor",
L"Activitate",
L"Lecție",
L"Elev",
L"Subactivitate",
L"Etichetă",
L"Spațiu",
L"Nume de familie",
L"Prenume",
L"Parametri",
L"Adaugă",
L"Nume",
L"Comentarii",
L"Ore",
L"Selectat",
L"Șterge",
L"Nume complet",
L"Cod",
L"Clădiri",
L"Clădire",
L"Săli",
L"Sală",
L"Infrastructură",
L"Capacitate",
L"Clase",
L"Numele instituției",
L"Zile",
L"Zi",
L"Fire",
L"Generează acum",
L"Se generează orarele...",
L"Clădire principală",
L"Opțiuni",
L"Ani",
L"An",
L"Grupuri",
L"Grup",
L"Subgrupuri",
L"Subgrup",
L"Sortează",
L"Câte orare să se genereze",
L"Număr de elevi",
L"Rezumat",
L"Deschide folderul cu rezultate",
L"Rezultate",
L"ID Grup",
L"Intervale indisponibile",
L"Filtru",
L"Activ",
L"Tip filtru",
L"Vizualizare",
L"Înregistrare",
L"Înregistrare nouă",
L"Procentaj",
L"Selectează",
L"Sală de bază",
L"Atribuiri",
L"Atribuire",
L"Avertizări",
L"Orar",
L"Constrângeri de timp obligatorii de bază",
L"Clasă",
L"Zile minime/săptămână",
L"Zile maxime/săptămână",
L"Activ",
L"Max. pauze/zi",
L"Max. pauze/săptămână",
L"Nicio activitate două zile consecutive",
L"Max. ore/zi",
L"Limite zilnice",
L"Limite săptămânale",
L"Durată maximă/zi",
L"Excepție de o zi",
L"Min. ore/zi",
L"Max. ore consecutive",
L"Importă CSV...",
L"Nume clădire,Cod clădire,Comentarii clădire",
L"Minute de așteptare",
L"Nume sală,Cod sală,Capacitate",
L"Număr de activități",
L"Nume copil,Cod copil",
L"Crearea elevilor nu este necesară pentru generarea orarului, dar este utilă pentru exportul pe elev.",
L"Doar citire",
L"Activat",
L"Dezactivat",
L"Exportă",
L"Pagină/Profesor",
L"Profesori/Săptămână",
L"Dezactivează constrângerile de timp",
L"Dezactivează constrângerile de spațiu",
L"Statistici",
L"Nivel 1",
L"Nivel 2",
L"Nivel 3",
L"Rulează",
L"Setări",
L"Fișiere Plan XY",
L"Aceasta este informația de bază pentru instituția dvs.",
L"Fiecare instituție are cel puțin o clădire și fiecare clădire are cel puțin o sală. Puteți adăuga sau importa clădiri și săli noi.",
L"Caută",
L"Puteți adăuga sau importa profesori pentru instituția dvs.",
L"Nume profesor,Ore profesor",
L"Puteți adăuga sau importa lecții pentru instituția dvs.",
L"Nume lecție,Cod lecție",
L"Puteți avea până la 3 niveluri de clasă.",
L"Etichetele sunt opționale. Sunt utile pentru a aplica anumite constrângeri de timp sau spațiu unui grup de activități.",
L"Atribuiți profesori la lecții și clase prin activități. Atribuirile simplifică crearea activităților selectând mai întâi un profesor.",
L"Atribuiți profesori la lecții și clase prin activități.",
L"Schimbări maxime de sală",
L"Schimbări maxime de sală (interval)",
L"De la",
L"Până la",
L"Schimbări maxime de clădire",
L"Schimbări maxime de clădire (interval)",
L"Despre",
L"Săli preferate",
L"Sală preferată",
L"Crearea părinților nu este necesară pentru generarea orarului, dar este utilă pentru exportul pe părinte.",
L"Părinți",
L"Părinte",
L"Nume părinte,Cod părinte",
L"Colaborare",
L"Partajează ecranul",
L"Alătură-te",
L"Copiază cheia în clipboard",
L"Se așteaptă utilizatori. Trimiteți-le cheia de invitație și mențineți această fereastră deschisă.",
L"Introduceți cheia de invitație:",
L"Mod",
L"Implicit",
L"ID unic",
L"Nume afișat",
L"Nicio activitate două zile consecutive",
L"Timpuri preferate de început",
L"La finalizare",
L"Repaus PC",
L"Oprire PC",
L"Generarea s-a încheiat. Oprirea în 1 minut.",
L"Intervale orare preferate",
L"Început/Sfârșit zi",
L"Timp",
L"Început zi de cursuri",
L"Sfârșit zi de cursuri",
L"Început/Sfârșit zi de cursuri",
L"Început zi profesor",
L"Sfârșit zi profesor",
L"Început/Sfârșit zi profesor",
L"Zile minime între",
L"Alte limite",
L"Pauze minime între schimbări de sală",
L"Pauze minime între schimbări de clădire",
L"Afișează doar înregistrările",
L"Bine ați venit la Plan XY.\r\nÎncepeți să proiectați orarul în fila 'Date' sau deschideți un exemplu existent din meniul Exemple.",
L"Exemple",
L"Culoare",
L"Exportă FET",
L"Timpuri preferate de început",
L"Caracteristici de ieșire",
L"Combinații de clase",
L"Acțiuni",
L"Proiectul a fost modificat. Salvați modificările?",
L"Ore/activitate",
L"Doriți să salvați proiectul mai întâi? Dacă generați orarul într-un proiect salvat, orarele generate vor fi salvate automat în fișierul proiectului.",
L"Sigur doriți să opriți generarea orarului?",
L"Înregistrări existente",
L"Înregistrare existentă",
L"Moment creare",
L"Durată",
L"Pauzat",
L"Pauze",
L"Clădire nouă",
L"Sală nouă",
L"Trebuie",
LR"(Zile maxime între)",
LR"(Început/Sfârșit de zi)",
LR"(Începutul zilei)",
LR"(Sfârșitul zilei)",
LR"(Coordonate)",
L"Editor manual",
L"Set de activități",
L"Aceeași oră de început",
L"Aceeași zi de început",
L"Aceeași oră+zi de început",
L"Start",
L"Fără suprapunere",
L"Set de etichete",
L"Importă",
L"Două sunt ordonate",
L"Două sunt ordonate (în aceeași zi)",
L"Două sunt consecutive",
L"Două sunt grupate",
L"Trei sunt grupate",
L"Durată maximă orară",
L"Intervale minime între",
L"Diverse",
L"Constrângere",
L"Constrângeri",
L"Ore minime de odihnă",
L"Circular",
L"Necunoscut",
L"Aceste constrângeri FET nu sunt încă recunoscute de PlanXY, dar pot fi editate manual",
L"Ocupă numărul maxim de intervale orare din selecție",
L"Intervale orare",
L"Număr maxim de intervale orare",
L"Deconectează",
L"Atașează",
L"Proiectul are date de execuție active, detașate. Gestionează aceste date în pagina „Rulare”.",
L"Gestionează datele detașate",
L"Sesiune",
L"Atașează și reia",
L"Termină",
L"Reluare",
L"Intervale orare mutual exclusive",
L"Pauză",
};

#define MAX_LANG 243