const wchar_t* z_strings_es[] = {L"",L"Plan XY",
L"No",
L"Sí",
L"OK",
L"Cancelar",
L"Claro/Oscuro",
L"Nuevo",
L"Abrir",
L"Guardar",
L"Guardar como...",
L"Salir",
L"Predeterminado",
L"Claro",
L"Oscuro",
L"Reinicie la aplicación para aplicar los cambios.",
L"Ayuda",
L"Principal",
L"Datos",
L"Restricciones de tiempo",
L"Restricciones de espacio",
L"Generador",
L"Archivo",
L"Básico",
L"Profesores",
L"Actividades",
L"Lecciones",
L"Estudiantes",
L"Subactividades",
L"Etiquetas",
L"Espacios",
L"Profesor",
L"Actividad",
L"Lección",
L"Estudiante",
L"Subactividad",
L"Etiqueta",
L"Espacio",
L"Apellido",
L"Nombre",
L"Parámetros",
L"Añadir",
L"Nombre",
L"Comentarios",
L"Horas",
L"Seleccionado",
L"Eliminar",
L"Nombre completo",
L"Código",
L"Edificios",
L"Edificio",
L"Aulas",
L"Aula",
L"Infraestructura",
L"Capacidad",
L"Clases",
L"Nombre de la institución",
L"Días",
L"Día",
L"Hilos",
L"Generar ahora",
L"Generando horarios...",
L"Edificio principal",
L"Opciones",
L"Años",
L"Año",
L"Grupos",
L"Grupo",
L"Subgrupos",
L"Subgrupo",
L"Ordenar",
L"Cuántos horarios generar",
L"Número de estudiantes",
L"Resumen",
L"Abrir carpeta de resultados",
L"Resultados",
L"ID de grupo",
L"Tiempos no disponibles",
L"Filtro",
L"Activo",
L"Tipo de filtro",
L"Vista",
L"Entrada",
L"Nueva entrada",
L"Porcentaje",
L"Seleccionar",
L"Aula base",
L"Asignaciones",
L"Asignación",
L"Advertencias",
L"Horario",
L"Restricciones básicas obligatorias de tiempo",
L"Clase",
L"Mín. días/semana",
L"Máx. días/semana",
L"Activo",
L"Máx. huecos/día",
L"Máx. huecos/semana",
L"No trabajar dos días consecutivos",
L"Máx. horas/día",
L"Límites diarios",
L"Límites semanales",
L"Máx. intervalo/día",
L"Excepción de un día",
L"Mín. horas/día",
L"Máx. horas continuas",
L"Importar CSV...",
L"Nombre edificio,Código edificio,Comentarios edificio",
L"Minutos de espera",
L"Nombre aula,Código aula,Capacidad",
L"Número de actividades",
L"Nombre niño,Código niño",
L"Crear estudiantes no es necesario para generar un horario, pero es útil para exportar por estudiante.",
L"Solo lectura",
L"Habilitado",
L"Deshabilitado",
L"Exportar",
L"Página/Profesor",
L"Profesores/Semana",
L"Desactivar restricciones de tiempo",
L"Desactivar restricciones de espacio",
L"Estadísticas",
L"Nivel 1",
L"Nivel 2",
L"Nivel 3",
L"Ejecutar",
L"Configuración",
L"Archivos Plan XY",
L"Esta es la información básica de su institución.",
L"Cada institución tiene al menos un edificio y cada edificio al menos un aula. Puede añadir o importar nuevos edificios y aulas.",
L"Buscar",
L"Puede añadir o importar profesores para su institución.",
L"Nombre profesor,Horas profesor",
L"Puede añadir o importar lecciones para su institución.",
L"Nombre lección,Código lección",
L"Puede tener hasta 3 niveles de clases.",
L"Las etiquetas son opcionales. Son útiles para aplicar ciertas restricciones de tiempo o espacio a un grupo de actividades.",
L"Asigna profesores a lecciones y clases mediante actividades. Las asignaciones facilitan crear actividades eligiendo primero un profesor.",
L"Asigna profesores a lecciones y clases mediante actividades.",
L"Cambios máximos de aula",
L"Cambios máximos de aula (intervalo)",
L"Desde",
L"Hasta",
L"Cambios máximos de edificio",
L"Cambios máximos de edificio (intervalo)",
L"Acerca de",
L"Aulas preferidas",
L"Aula preferida",
L"Crear padres no es necesario para generar un horario, pero es útil para exportar por padre.",
L"Padres",
L"Padre",
L"Nombre padre,Código padre",
L"Colaboración",
L"Compartir pantalla",
L"Unirse",
L"Copiar clave al portapapeles",
L"Esperando usuarios. Envíeles la clave de invitación y mantenga esta ventana abierta.",
L"Ingrese la clave de invitación:",
L"Modo",
L"Predeterminado",
L"ID único",
L"Nombre para mostrar",
L"No dos días consecutivos",
L"Tiempos de inicio preferidos",
L"Al finalizar",
L"Suspender PC",
L"Apagar PC",
L"Generación completada. Apagando en 1 minuto.",
L"Franjas horarias preferidas",
L"Inicio/Fin del día",
L"Hora",
L"Inicio día de clases",
L"Fin día de clases",
L"Inicio/Fin día de clases",
L"Inicio día del profesor",
L"Fin día del profesor",
L"Inicio/Fin día del profesor",
L"Mín. días entre",
L"Otros límites",
L"Mín. huecos entre cambios de aula",
L"Mín. huecos entre cambios de edificio",
L"Mostrar solo entradas",
L"Bienvenido a Plan XY.\r\nComience a diseñar su horario en la pestaña 'Datos', o abra un ejemplo existente desde el menú Ejemplos.",
L"Ejemplos",
L"Color",
L"Exportar FET",
L"Tiempos de inicio preferidos",
L"Características de salida",
L"Combinaciones de clases",
L"Acciones",
L"El proyecto ha sido modificado. ¿Desea guardar los cambios?",
L"Horas/actividad",
L"¿Guardar primero el proyecto? Si genera un horario en un proyecto guardado, los horarios generados se guardarán automáticamente en el archivo del proyecto.",
L"¿Está seguro de que desea detener la generación del horario?",
L"Entradas existentes",
L"Entrada existente",
L"Hora de creación",
L"Duración",
L"Pausado",
L"Huecos",
L"Nuevo edificio",
L"Nueva aula",
L"Debe",
LR"(Días máximos entre)",
LR"(Inicio/Fin del día)",
LR"(Inicio del día)",
LR"(Fin del día)",
LR"(Coordenadas)",
L"Editor manual",
L"Conjunto de actividades",
L"Misma hora de inicio",
L"Mismo día de inicio",
L"Misma hora+día de inicio",
L"Iniciar",
L"Sin solapamiento",
L"Conjunto de etiquetas",
L"Importar",
L"Dos están ordenadas",
L"Dos están ordenadas (mismo día)",
L"Dos son consecutivas",
L"Dos están agrupadas",
L"Tres están agrupadas",
L"Máxima duración horaria",
L"Intervalos mínimos entre",
L"Varios",
L"Restricción",
L"Restricciones",
L"Horas mínimas de descanso",
L"Circular",
L"Desconocido",
L"Estas restricciones de FET aún no son reconocidas por PlanXY, pero puede editarlas manualmente",
L"Ocupar el número máximo de franjas horarias de la selección",
L"Franjas horarias",
L"Máximo de franjas horarias",
L"Desvincular",
L"Vincular",
L"El proyecto tiene datos activos separados en ejecución. Gestione los datos en la página 'Ejecutar'.",
L"Gestionar datos separados",
L"Sesión",
L"Vincular y reanudar",
L"Terminar",
L"Reanudar",
L"Franjas horarias mutuamente excluyentes",
L"Descanso",
};

#define MAX_LANG 243