import "Item.idl";
import "DGRowModel.idl";
import "DGCellModel.idl";
import "DGHeaderModel.idl";



namespace WuiFET
{
    [default_interface]
    runtimeclass Statistics : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Statistics();
        static String txt(Int32 sidx);
        void Refresh();
        Int64 ResultX;
        Int64 ResultP;
        Int32 Mode;
        Boolean IsM1{ get; };
        Boolean IsM2{ get; };

        Windows.Foundation.Collections.IObservableVector<DGHeaderModel> gr1_ch{ get; };
        Windows.Foundation.Collections.IObservableVector<DGRowModel> gr1_is{ get; };
    }
}
        