namespace WuiFET
{
    [default_interface]
    runtimeclass ViewResult : Microsoft.UI.Xaml.Window, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ViewResult();
        static String txt(Int32 sidx);
        void Refresh();
        Int64 ResultX;
        Int64 ResultP;
    }
}
