import "Item.idl";
import "DGRowModel.idl";
import "DGCellModel.idl";
import "DGHeaderModel.idl";

namespace WuiFET
{
    [default_interface]
    runtimeclass Constraints : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Constraints();
        static String txt(Int32 sidx);
        void Refresh();

        Double Resizer_V1;
        Microsoft.UI.Xaml.GridLength Resizer_VV1{ get; };
        Windows.Foundation.Collections.IObservableVector<Item> Left_List{ get; };

        String str1;
        String str2;
        String str3;
        String str4;
		Boolean OnlyShowEntries;
        Int32 ConstraintsMode{ get; };
        Boolean IsTS{ get; };
        Boolean IsSS{ get; };

        Microsoft.UI.Xaml.Controls.ListViewSelectionMode leftsm{ get; };


        Boolean IsLeftVisible{ get; };
        Boolean IsRightVisible{ get; };
        Boolean IsActiveVisible{ get; };
        Boolean IsActiveChecked;
        Boolean IsMultiple{ get; };
        Boolean IsPercentageVisible{ get; };
		Int32 Percentage;
        Boolean IsGridRightVisible{ get; };
		Boolean IsListRightVisible{ get; };
        Windows.Foundation.Collections.IObservableVector<DGHeaderModel> zz1_ch{ get; };
        Windows.Foundation.Collections.IObservableVector<DGRowModel> zz1_is{ get; };
        Windows.Foundation.Collections.IObservableVector<Item> Right_List{ get; };


    }
}
